config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :to_dos do
    patch :update_position, on: :collection
    get :completed, on: :collection
  end

  root 'to_dos#index'

end

app/models/to_do.rb
class ToDo < ActiveRecord::Base
  validates_presence_of :title
  include RankedModel
  ranks :position

def self.set_position
  last = ToDo.rank(:position).last
  if last == nil
    1
  else
    last.position + 1
  end
end

  # def sort
  #   @todo_list = ToDo.all
  #   @todo_list.each do |f|
  #     f.position = params["sortable"].index(f.id.to_s)+1
  #     f.save
  #   end
  # end

  def self.search(search)
    if search == ""
      all
    else
      where('title LIKE ?', "%#{search}%")
    end
  end

  def self.incomplete
    ToDo.where(complete: [false, nil])
  end

  def self.completed
    ToDo.where(complete: true)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session,
  if: Proc.new { |c| c.request.format =~ %r{application/json} }
end

app/controllers/to_dos_controller.rb
class ToDosController < ApplicationController
  before_action :authenticate_user!

  def index
    # @todos= ToDo.rank(:position).all
    @todos= ToDo.search(params[:search]).rank(:position).where(user_id: current_user.id).all
  end

  def new
    @todo = ToDo.new
  end

  def create
    @todo = ToDo.new(todo_params)
    @todo.position = ToDo.set_position
    @todo.save
    redirect_to to_dos_path
    flash[:notice] = "ToDo created."
  end

  def show
  end

  def edit
  end

  def update
    @todo = ToDo.find_by_id(params[:id])
    ToDo.update(@todo.id, complete: params[:complete])
  end

  def update_position
    @todo = ToDo.find_by_id(params[:id])
    ToDo.update(@todo.id, position: params[:position])
    render nothing: true
  end

  def completed
    @todos=ToDo.where(user_id: current_user.id).all
  end

  def destroy
  end

  private

    def todo_params
      params.require(:to_do).permit(:title, :description, :due_at, :position, :category, :id, :complete, :search, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/to_dos_helper.rb
module ToDosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag image_path('favicon.ico') %>
</head>

<body>
  <p id="notice"><%= notice %></p>

<%= yield %>

</body>
</html>

app/views/to_dos/_complete_list.html.erb
<% @todos.completed.each do |todo| %>
    <h3><%= todo.title %></h3>
    <%= form_for todo do |f|%>
      <%= f.hidden_field :id, class: "rails-id" %>
      <% unless todo.description.empty?  %>
        <p><h4>Description: </h4><%= todo.description %></p>
      <% end %>
      <% unless todo.description.empty?  %>
        <p><h4>Category:    </h4><%= todo.category %></p>
      <% end %>
      <%  if todo.due_at %>
        <p><h4>Due Date:  </h4><%= local_time(todo.due_at) %></p>
      <% end %>
      <h4>Completed </h4>
    <% end %>
<% end %>

app/views/to_dos/_form.html.erb
<div id = "new-form">
  <%= form_for @todo do |f| %>
    <%= f.hidden_field :user_id, :value=> current_user.id %><br>

    <%= f.text_field :title, placeholder: "Title" %><br>

    <%= f.text_area :description, placeholder: "Description" %><br>

    <%= f.text_field :category, placeholder: "Category" %><br>

    <%= f.datetime_select :due_at, placeholder: "Due At", ampm: true, include_blank: true  %>

    <%= f.submit "Create ToDo" %>
  <% end %>
</div>

app/views/to_dos/_to_dos.html.erb
<table class="table table-bordered table-striped" id="sortable">
  <thead>
    <tr>
      <th>
        ToDos
      </th>
    </tr>
  </thead>
  <tbody>
    <% @todos.incomplete.each do |todo| %>
      <tr data-item-id=<%= "#{todo.id}" %> class="item">
        <td style= "cursor:move">
        <h3><%= todo.title %></h3>
        <%= form_for todo do |f|%>
          <%= f.hidden_field :id, class: "rails-id" %>
          <% unless todo.description.empty?  %>
            <p><h4>Description: </h4><%= todo.description %></p>
          <% end %>
          <% unless todo.description.empty?  %>
            <p><h4>Category:    </h4><%= todo.category %></p>
          <% end %>
          <%  if todo.due_at %>
            <p><h4>Due Date:  </h4><%= local_time(todo.due_at) %></p>
          <% end %>
          <h4> Mark Complete: </h4><%=f.check_box :complete, class: "to-do-complete" %>
        <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div id = "new-and-completed-todo">
  <p>Welcome to Crash ToDos! To create a new ToDo item, please click below.</p>
  <%= link_to "New", new_to_do_path, remote: true %>
  <div id ="new-form"></div>
  <div id = "completed-todos">
    <%= link_to "See Completed ToDos", completed_to_dos_path, remote: true %>
    <div id="completed"></div>
  </div>
</div>

app/views/to_dos/completed.js.erb
$("#completed").html("<%= j(render 'complete_list') %>");

app/views/to_dos/index.html.erb
<%= link_to "Sign Out", destroy_user_session_path, :method => :delete, id: "sign-out"   %>
<h1 class= "title"> Crash ToDos</h1>
  <div class="to-dos-form">
    <%= form_tag to_dos_path, :method => 'get', id: "todos-search" do %>
      <span>
        <%= text_field_tag :search, params[:search], placeholder: "Search ToDos!" %>
      </span>
      <% end %>
    <div id= "text_block">
      <%= render 'to_dos' %>
    </div>
  </div>

app/views/to_dos/index.js.erb
$("#text_block").html("<%= escape_javascript(render("to_dos")) %>");

app/views/to_dos/new.js.erb
$("#new-form").html("<%= j(render 'form') %>");

app/views/to_dos/update.js.erb
$("#to-do-complete").val(true);